# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QT\corona_disease_detection\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from images import covid
from DBconn import DBConnection
import mysql.connector
import xlrd
import sys
from upload import upload
from classifcation import classfy
from performance import view_data


class admin(object):
    def performance(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = view_data()
        self.ui.setupUi(self.Dialog)
        self.ui.performance()
        self.Dialog.show()
    def graph(self):
        classfy()
    def upload(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = upload()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1225, 800)
        Dialog.setStyleSheet("QDialog{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.752632 rgba(102, 47, 118, 232), stop:1 rgba(255, 255, 255, 255));}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1225, 71))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(140, 23, 56, 173), stop:1 rgba(255, 255, 255, 255));\n"
"font: 18pt \"Bauhaus 93\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(202, 365, 229, 231))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-image: url(:/dialog/upload (2).png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 370, 231, 226))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-image: url(:/dialog/graph.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(833, 370, 231, 226))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-image: url(:/dialog/performance.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.upload)
        self.pushButton_2.clicked.connect(self.graph)
        self.pushButton_3.clicked.connect(self.performance)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ADMIN>>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = admin()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
