# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QT\corona_disease_detection\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from images import covid
from signup import signup
from admin import admin
from DBconn import DBConnection
from predictor import predict


class login(object):


    def alertmsg2(self, title, Message):
        self.warn = QtWidgets.QMessageBox()
        self.warn.setIcon(QtWidgets.QMessageBox.Information)
        self.warn.setWindowTitle(title)
        self.warn.setText(Message)
        self.warn.setStandardButtons(QtWidgets.QMessageBox.Ok)
        self.warn.setWindowIcon(QtGui.QIcon('D:\\111 _MACHINE_LEARNING\\033_Corona_Virus_Infection_detection_SVM\images\error.png'))
        self.warn.exec_()
    def alertmsg(self, title, Message):
        self.warn = QtWidgets.QMessageBox()
        self.warn.setIcon(QtWidgets.QMessageBox.Information)
        self.warn.setWindowTitle(title)
        self.warn.setText(Message)
        self.warn.setStandardButtons(QtWidgets.QMessageBox.Ok)
        self.warn.setWindowIcon(QtGui.QIcon('D:\\111 _MACHINE_LEARNING\\033_Corona_Virus_Infection_detection_SVM\images\error.png'))
        self.warn.exec_()

    def admin(self):
        uid = self.lineEdit.text()
        passw = self.lineEdit.text()
        if uid == "admin" or passw == "admin":
            self.Dialog = QtWidgets.QDialog()
            self.ui = admin()
            self.ui.setupUi(self.Dialog)
            self.Dialog.show()

    def log(self):
        uid = self.lineEdit.text()

        passw = self.lineEdit_2.text()

        mydb = DBConnection.getConnection()
        cursor = mydb.cursor()
        query = "SELECT username,password FROM patient_details  WHERE username = (%s) AND password = (%s) "
        cursor.execute(query, (uid, passw))

        if (len(cursor.fetchall()) > 0):
            self.Dialog = QtWidgets.QDialog()
            self.ui = predict()
            self.ui.setupUi(self.Dialog)
            self.Dialog.show()
        elif uid=="null" or uid=="" or passw=="null" or passw=="":
            self.alertmsg2("failed", "Please enter all the required fields")
        elif uid=="admin" or passw=="admin":
            pass
        else:
            self.alertmsg("failed", "Please enter enter the correct details")

    def registration(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = signup(self.Dialog)
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1225, 800)
        Dialog.setStyleSheet("\n"
"QDialog{background-image: url(:/dialog/dialog.jpg);}\n"
"")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(386, 122, 391, 511))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(244, 255, 213, 219), stop:1 rgba(255, 255, 255, 255));")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(460, 130, 231, 101))
        self.label_2.setStyleSheet("font:18pt \"Arial\";")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(460, 269, 231, 41))
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(194, 194, 194, 188), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 17pt \"Arial\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(460, 359, 231, 41))
        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(194, 194, 194, 188), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 17pt \"Arial\";")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(650, 270, 41, 40))
        self.label_3.setStyleSheet("background-image: url(:/dialog/login_icon.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(650, 360, 41, 38))
        self.label_4.setStyleSheet("background-image: url(:/dialog/password_ico.jpg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(500, 430, 151, 51))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(200, 59, 115);\n"
"font: 75 20pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(440, 480, 151, 71))
        self.label_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(95, 95, 95);")
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(534, 486, 181, 61))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 131, 0);")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton_2.clicked.connect(self.registration)
        self.pushButton.clicked.connect(self.admin)
        self.pushButton.clicked.connect(self.log)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "LOGIN"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Password"))
        self.pushButton.setText(_translate("Dialog", "LOGIN"))
        self.label_5.setText(_translate("Dialog", "Not registered?"))
        self.pushButton_2.setText(_translate("Dialog", "Registered Here"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = login()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
