# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QT\corona_disease_detection\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from images import covid
from DBconn import DBConnection


class signup(object):
    def __init__(self, dialog):
        self.Dialog = dialog
    def alertmsg2(self, title, Message):
        self.warn2 = QtWidgets.QMessageBox()
        self.warn2.setIcon(QtWidgets.QMessageBox.Information)
        self.warn2.setWindowTitle(title)
        self.warn2.setText(Message)
        self.warn2.setStandardButtons(QtWidgets.QMessageBox.Ok)
        self.warn2.setWindowIcon(QtGui.QIcon('D:\\111 _MACHINE_LEARNING\\033_Corona_Virus_Infection_detection_SVM\images\error.png'))
        self.warn2.exec_()
    def alertmsg(self, title, Message):
        self.warn2 = QtWidgets.QMessageBox()
        self.warn2.setIcon(QtWidgets.QMessageBox.Information)
        self.warn2.setWindowTitle(title)
        self.warn2.setText(Message)
        self.warn2.setStandardButtons(QtWidgets.QMessageBox.Ok)
        self.warn2.setWindowIcon(QtGui.QIcon('D:\\111 _MACHINE_LEARNING\\033_Corona_Virus_Infection_detection_SVM\images\ok.png'))
        self.warn2.exec_()
    def regis(self):
        try:
            uid = self.lineEdit.text()
            passw = self.lineEdit_2.text()
            name = self.lineEdit_3.text()

            mydb = DBConnection.getConnection()
            cursor = mydb.cursor()
            query = "INSERT INTO  patient_details (username,password,name) VALUES (%s,%s,%s)"
            val = (uid,passw,name)
            if  uid == '' or uid == "null" or passw == '' or passw == "null" or name == '' or name == "null" :
                self.alertmsg2("failed", "Please fill the All Details")
            else:
                cursor.execute(query, val, )
                mydb.commit()
                cursor.close()
                mydb.close()
                self.alertmsg("Successfull", "Registered")
                self.Dialog.hide()
        except Exception as e:
            print("Error=" + e.args[0])
            tb = sys.exc_info()[2]
            print(tb.tb_lineno)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1225, 800)
        Dialog.setStyleSheet("QDialog{background-image: url(:/dialog/dialog.jpg);}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 110, 961, 601))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 99, 150, 89), stop:1 rgba(255, 255, 255, 255));")
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 510, 181, 51))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(200, 59, 115);\n"
"font: 75 20pt \"Agency FB\";")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 360, 271, 41))
        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 79), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 17pt \"Arial\";")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 440, 281, 41))
        self.lineEdit_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 79), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 17pt \"Arial\";")
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_3.setMaxLength(30)
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(260, 280, 271, 41))
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 122, 122, 79), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 17pt \"Arial\";")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 170, 271, 71))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 17pt \"Segoe UI Black\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(614, 112, 485, 596))
        self.label_3.setStyleSheet("background-image: url(:/dialog/signup.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.regis)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Register"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "password"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "name"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "username"))
        self.label_2.setText(_translate("Dialog", "Create Account"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = signup(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
