# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QT\corona_disease_detection\upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from images import covid
from DBconn import DBConnection
import sys
import xlrd


class upload(object):
    def alertmsg(self, title, Message):
        self.warn = QtWidgets.QMessageBox()
        self.warn.setIcon(QtWidgets.QMessageBox.Information)
        self.warn.setWindowTitle(title)
        self.warn.setText(Message)
        self.warn.setStandardButtons(QtWidgets.QMessageBox.Ok)
        self.warn.setWindowIcon(QtGui.QIcon('D:\\111 _MACHINE_LEARNING\\033_Corona_Virus_Infection_detection_SVM\images\ok.png'))
        self.warn.exec_()
    def alertmsg2(self, title, Message):
        self.warn = QtWidgets.QMessageBox()
        self.warn.setIcon(QtWidgets.QMessageBox.Information)
        self.warn.setWindowTitle(title)
        self.warn.setText(Message)
        self.warn.setStandardButtons(QtWidgets.QMessageBox.Ok)
        self.warn.setWindowIcon(QtGui.QIcon('D:\\111 _MACHINE_LEARNING\\033_Corona_Virus_Infection_detection_SVM\images\error.png'))
        self.warn.exec_()

    def browse_file(self):
        try:
            fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Select File", "*.xlsx")

            print(fileName)
            self.lineEdit.setText(fileName)
        except Exception as e:
            print("Error=" + e.args[0])
            tb = sys.exc_info()[2]
            print(tb.tb_lineno)

    def saveToDB(self):
        try:
            fname = self.lineEdit.text()
            if fname=="null" or fname=="":
                self.alertmsg2("Error", "Please select the file")
            else:

                book = xlrd.open_workbook(fname)
                sheet = book.sheet_by_index(0)
                query = "delete from covid_health"
                mydb = DBConnection.getConnection()
                cursor = mydb.cursor()
                cursor.execute(query)
                mydb.commit()
                query = "insert into covid_health values(%s,%s,%s,%s,%s,%s)"
                for r in range(1, sheet.nrows):
                    AGE = sheet.cell(r, 0).value
                    BODY_TEMP = sheet.cell(r, 1).value
                    BODY_PAIN = sheet.cell(r, 2).value
                    RUNNY_NOSE_STATUS = sheet.cell(r, 3).value
                    BREATHING_PROBLEM = sheet.cell(r, 4).value
                    TEST_RESULT = sheet.cell(r, 5).value

                    print(AGE, BODY_TEMP, BODY_PAIN, RUNNY_NOSE_STATUS, BREATHING_PROBLEM, TEST_RESULT)
                    values = (int(AGE), int(BODY_TEMP), int(BODY_PAIN), int(RUNNY_NOSE_STATUS), int(BREATHING_PROBLEM),
                              int(TEST_RESULT))

                    mydb = DBConnection.getConnection()
                    cursor = mydb.cursor()
                    cursor.execute(query, values)
                    mydb.commit()
                    cursor.close()
                    mydb.close()

                    print("inserted")
                self.alertmsg("Uploaded Successfully", "DataSet Loaded Successfully")
                self.lineEdit.setText("")
        except Exception as e:
            print("Error=" + e.args[0])
            tb = sys.exc_info()[2]
            print(tb.tb_lineno)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1225, 800)
        Dialog.setStyleSheet("QDialog{background-image: url(:/dialog/resized-image-Promo.jpeg);}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(270, 50, 871, 631))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(111, 133, 120, 127), stop:1 rgba(255, 255, 255, 255));")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(420, 340, 161, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(581, 340, 421, 41))
        self.lineEdit.setStyleSheet("font: 75 italic 12pt \"Arial\";")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 410, 161, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(177, 177, 177);\n"
"font: 12pt \"Arial\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(570, 210, 271, 81))
        self.label_2.setStyleSheet("font: 87 16pt \"Arial Black\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 132, 56, 196), stop:1 rgba(255, 255, 255, 255));")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.browse_file)
        self.pushButton_2.clicked.connect(self.saveToDB)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Choose File"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "no file selected"))
        self.pushButton_2.setText(_translate("Dialog", "Upload"))
        self.label_2.setText(_translate("Dialog", "Upload Dataset"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = upload()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
